### PR TITLE
Keep Linux capitalization consistent.

### PR DESCRIPTION
**Pull request by pbardea**
# The Linux/LInux Capitalization Controversy 

## Summary
As a reader of this fabulous README, I would like all occurrences of the work "Linux" to have consistent capitalization. On all other occurrences other than the altered one the capitalization of the work "Linux" has been "Linux". I believe that even when referred to properly as "GNU/Linux" the capitalization should remain consistent with the other occurrences of "Linux". To resolve this issue there are 2 possible fixes.

## Possible changes
1) First, change the occurrence of "LInux" to "Linux" as done in this Pull Request.
**This is the recommended change.**

The advantages to this approach include:
- Minimal changes
- Consistent with other uses on the Internet [1] [2] [3] [4] [5]

2) Second, change all other occurrences of "Linux" to "LInux".

This approach is not recommended for a couple of reasons: 

a) Λesthetically, it is not as pleasing to the eye. A survey of 10,000 developers [6] have shown that the "Linux" capitalization is clearly superior.
b) As alluded to in the first option, the capitalization of "LInux" is not popular on the Internet, and as such people reading this fabulous README may not be familiar with the term if it is capitalized as "LInux". Furthermore, it may cause confusion as people may think (incorrectly I imagine) that the capitalized "L" and "I" in fact stand for something as is oft the case when more than one letter in a word is capitalized. As GNU itself, is in fact an acronym.

## Conclusion

Therefore I submit this Pull Request for your review. I am looking forward to a fruitful discussion about this very important topic as you deem fit. I hope you have a lovely weekend.

## Works Cites

[1] https://en.wikipedia.org/wiki/GNU/Linux_naming_controversy
[2] https://www.gnu.org/gnu/linux-and-gnu.en.html
[3] https://www.debian.org/releases/lenny/i386/ch01s02.html.en
[4] https://en.wikipedia.org/wiki/GNU
[5] http://getgnulinux.org/en/home/
[6]
official gnu linux survey

NB: Full APA citation not used because this is a pull request, and that is the limit I am going to go for the 'meme'ability of a Pull Request. Feel free to edit if you are so inclined. :)

### CODE REVIEW

**Comment by pbardea** [comment]
@AndrewMcBurney Please consider giving this your full attention please as I feel it is a very pressing issue in today's society.

**Review by armcburney — APPROVED** [review]
🙏👏😭😂😳👍🏼💯

**Comment by armcburney** [comment]
As for 'fruitful discussion': 🍉🍌🍓🍍🍒🍇🍎🍋🍊🍑🍏🍅🍐🍈🥝

**Comment by pbardea** [comment]
@AndrewMcBurney Don't have merge rights to this repo. You'll need to merge it. 👍

**Comment by armcburney** [comment]
@pbardea  Oops, lol forgot that ahahha

**Pull request merged**
